name: Deploy to GitHub Pages

on:
  push:
    branches: 'main' # Triggers the build every time you push changes to main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install project dependencies
        run: npm ci

      - name: Inject 404 fallback for routing safety
        run:  FIRST_HTML=$(find .output/public -name "index.html" | head -n 1)
          if [ -n "$FIRST_HTML" ]; then
            cp "$FIRST_HTML" .output/public/404.html
            echo "Successfully created 404.html fallback from $FIRST_HTML"
          else
            echo "Warning: No index.html found to clone."
          fi

      - name: Inject 404 fallback for routing safety
        run: cp .output/public/index.html .output/public/404.html

      - name: Configure GitHub Pages assets
        uses: actions/configure-pages@v5

      - name: Upload compiled static website
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.output/public' # Points directly to TanStack Start's static folder

      - name: Deploy to GitHub Pages Production
        id: deployment
        uses: actions/deploy-pages@v4
